### PR TITLE
start background complete

### PR DESCRIPTION
**Pull request by onon1101**
# config
you need to config here to resize window
```hpp
// PTSD/include/config.hpp
#ifndef CONFIG_H
#define CONFIG_H

#include "pch.hpp" // IWYU pragma: export

#include "Util/Logger.hpp"

constexpr const char *TITLE = "Practical Tools for Simple Design";

constexpr int WINDOW_POS_X = SDL_WINDOWPOS_UNDEFINED;
constexpr int WINDOW_POS_Y = SDL_WINDOWPOS_UNDEFINED;

//constexpr unsigned int WINDOW_WIDTH = 1280;
//constexpr unsigned int WINDOW_HEIGHT = 720;
constexpr unsigned int WINDOW_WIDTH = 1440;
constexpr unsigned int WINDOW_HEIGHT = 810;
//constexpr unsigned int IMAGE_RATIO = 3;
constexpr Util::Logger::Level DEFAULT_LOG_LEVEL = Util::Logger::Level::DEBUG;

/**
 * @brief FPS limit
 *
 * Set value to 0 to turn off FPS cap
 */
constexpr unsigned int FPS_CAP = 60;

#endif
```

image

### CODE REVIEW

**Comment by ruien0412** [comment]
Do we need to use different types of files in the assets and resources folders?

**Comment by onon1101** [comment]
我個人是比較偏好`assets` 因為看其他repo 都是這樣命名的 `resource` 比較少

**Comment by ruien0412** [comment]
因為目前已經有 `Resources` 了，那之後都統一為 `assets` 嗎

**Comment by onon1101** [comment]
好啊

**Review by ruien0412 — APPROVED** [review]

**Pull request closed without merging**
